### ISSUE TITLE
Can "multi-core compression" use a specified number of cores?

### ISSUE THREAD

**Issue by Petross404** [tritonas00/system-tar-and-restore#10]
[Here](https://github.com/jnovy/pxz/blob/master/pxz.c) I can see that "`--threads`" option, sets the maximux number of cores to use for compression. Is it possible that system-tar-and-restore, reads an input from the user to append there?

I suppose the other compression tools support something like this.

**Comment by tritonas00** [comment]
please search if pigz and pbzip2 also support this feature

if yes i will implement it

**Comment by tritonas00** [comment]
ok all support this, so i will implement it globally

**Comment by tritonas00** [comment]
Done: https://github.com/tritonas00/system-tar-and-restore/commit/0aac10d7da0653864d420a2dfbf258cd2123a803

Please test

**Comment by Petross404** [comment]
Hi. I will test later in the noon because I will be out of town.

Thank you tritona

**Comment by Petross404** [comment]
Magnificent! 

For now actuall compression hasn't started yet to actually see how many cores are busy, but I don't think there will be any issue.

**Comment by Petross404** [comment]
> see how many cores are busy, but I don't think there will be any issue.

I set the thread's value to 2 and 2 cores are working on it. Nice feature ;)

**Comment by Petross404** [comment]
Something minor for another release, could be that `nproc` (from coreutils) should give the maximum _allowed_ threads number and the user couldn't increment the "Number of threads" above that, or would get an warning.

**But it's not something usefull**; everyone know how many cores their cpu has.

**Comment by tritonas00** [comment]
> Something minor for another release, could be that nproc (from coreutils) should give the maximum allowed threads number and the user couldn't increment the "Number of threads" above that, or would get a warning.

I will take a look

**Comment by Petross404** [comment]
It's more of an excersise (not that you need to do one) or just an idea... Maybe the parallel compressor check themselves for such a thing.

But anyway, as you like. :)

**Comment by tritonas00** [comment]
Done: https://github.com/tritonas00/system-tar-and-restore/commit/93bbeaf78b2d3af867817b21e403c14369e9e895

**Comment by Petross404** [comment]
Also works :)

It doesn't allow me to increment above 6 (as I have a phenom II). Cool.

**Comment by Petross404** [comment]
Should this thread be closed?
