### ISSUE TITLE
Can system-tar-and-restore support compressing other partitions explicitly specified?

### ISSUE THREAD

**Issue by Petross404** [tritonas00/system-tar-and-restore#11]
I have different partitions for my root (/) directory and my home dir (/home). Also I have other (Linux and data) partitions that I'd like to compress from top directory and take backup with system-tar-and-restore.

Now, only a field "Destination" is provided in order to set the store location. Could a field "Target" or something be created in order to _explicitly_ define which directory the tarring should begin?? 

I know that this can be set from additional options (?) but it would be super easy and straightforward even for the noobest user.

**Comment by tritonas00** [comment]
star makes a tar backup of the running / (hard coded)

do you mean an option to change / to a desired location?

**Comment by Petross404** [comment]
> do you mean an option to change / to a desired location? 

Yes, I mean exactly that. :) To overide it with a field like "Target" or something. But again for conviniency star may not ask the user at all to fill in the target manually. Instead the user could tick a checkbox like "Set target manually" and a field would be enabled to accept the top directory of whatever the user needs to backup.

**Comment by Petross404** [comment]
For example I might want to compress my /home/$USER seperatally. Or I might want to compress just ~/Documents or /mnt/Data/MyMovies and store them to a large partition, specified by "Destination". 

What do you think of this? :)

**Comment by tritonas00** [comment]
I was thinking this a lot time ago. The ability to change the source from / would give several advantages:

1. Backup specified locations

2. Backup/Transfer another system ! (e.g a remote one in local network mounted via ssh to a local dir)

But, this would be a really massive code change and needs a lot of testing.

What can i do safely:

1. The user could specify the source from / to something else

2. If the above is true, the script will bypass all default tar options (--exclude /var /sys etc...) and create only a **non** restorable backup archive in the destination.

3. The End :smile:

**Comment by Petross404** [comment]
> a non restorable backup archive in the destination.  

Non restorable? That means it can't be decompressed?

Anyway what you describe as safe choise, I think is very feasible and reasonable too. For backing up Linux systems one can append the exclude options manually; if backing up something completely different, there is nothing to exclude (like /dev etc) and voila!

**Comment by tritonas00** [comment]
> Non restorable? That means it can't be decompressed?

Restore mode expects a **system** backup archive so it can chroot and do some stuff after the restore.

If you give it an archive of your /mnt/Data/MyMovies then... strange things will happen :smiley:

Also Restore mode expects a target root partition. Will you extract a /mnt/Data/MyMovies archive into a target root partition?

This project targets a **system** backup restore/transfer, its not designed for this, although it can be done via --excludes

**Comment by Petross404** [comment]
> Restore mode expects a system backup archive so it can chroot and do some stuff after the restore.

I see. ;) 

> This project targets a system backup restore/transfer, its not designed for this, although it can be done via --excludes

You are right, yes of course.

**Comment by tritonas00** [comment]
> Non restorable? That means it can't be decompressed?

Yes, of course it will be decompressed, but from you via an archive manager, not from star's restore mode

**Comment by tritonas00** [comment]
It works :stuck_out_tongue_winking_eye:

![2017-03-28-223254_1920x1080_scrot](https://cloud.githubusercontent.com/assets/2660424/24423906/5cbdf10e-1407-11e7-890e-401eaa6f0f30.png)

I will push when it's ready.

**Comment by tritonas00** [comment]
Please test: https://github.com/tritonas00/system-tar-and-restore/commit/f6e1c3674ef3eff2ea0f29cc2850e0710c10c223

**Comment by Petross404** [comment]
Will do, right now

**Comment by Petross404** [comment]
Yes, it works. I ran star-gui.sh, not the cli version. It's a wrapper so...

Although _not star-specific_, but my archive doesn't include **just** the parent directories. Instead of having just "photos", when I use ark to open the archive, I see "mnt->Volume_3->photos". When I decompress this archive in `/path/Data/`, I will get `/path/Data/mnt/Volume_3/photos` instead of `/path/Data/photos`.

As I said, this is not your fault, it is the way tar works but it should be best to be solved via some "Additional option" or something.

One way that is described [here](http://unix.stackexchange.com/questions/168357/creating-a-tar-archive-without-including-parent-directory), is to `cd` in the directory you want to compress. This would suffice with `star.sh` but not with the GUI wrapper. Besides it is not the most elegant and simple solution.

So I am asking out of curiosity, do you know a way to avoid including **all** the parent directories? Allthough I have to admit it is bedtime and I didn't test the `-C` option that is proposed in the link I gave.

**Comment by tritonas00** [comment]
No problem i think, i will do it tomorrow

**Comment by tritonas00** [comment]
Done: https://github.com/tritonas00/system-tar-and-restore/commit/9221cda84bffda3df29cb850a5f2a5916da570ce

**Comment by Petross404** [comment]
I will test it later in the morning :)

**Comment by Petross404** [comment]
Yes, it works :)
