### ISSUE TITLE
Tips & Tricks : How to extent "Additional Options" and "Exclude" permanently?

### ISSUE THREAD

**Issue by Petross404** [tritonas00/system-tar-and-restore#12]
I am looking for a way to add additional excludes to the existing list. I tried to edit both `/etc/conf.d/system-tar-and-restore.conf` and `/usr/share/system-tar-and-restore/backup.example.conf` but whem I try to actually compress a tar, backup.log doesn't have my options.

Of course one can always extend the defaults from the proper fields but if frequent backups have to be taken, or the exclude-list is big, it's much more convinient to "store" the program's preferences.

Either I installed the files in a wrong directory with a wrong filename, or I am missing something here.

PS: Let me know if using pastebin to show my confs will help.

**Comment by tritonas00** [comment]
How do you run star.sh?

**Comment by Petross404** [comment]
> By default star reads /etc/backup.conf

Hmm, therein lies the problem. I don't install it in this directory with this name. I thought it was a very generic name in a not-so-proper directory (at least for my distro, gentoo) so I installed it in `/etc/conf.d/` as `system-tar-and-restore.conf`. 

I think I can create and bundle a **patch** for the ebuild so when installing, star.sh will be patched with the new directory and filename, _only_ for Gentoo of course. It's plain Bash as I can tell, so it won't be difficult to look up in your code :)

> Did you tell star.sh or star-gui.sh to use those files?  

I am afraid no. Also most of the times I run star-gui.sh from the terminal which has root privileges, because I always have such a terminal open and I find it faster to start and test the program. :)

**Comment by tritonas00** [comment]
try `star-gui.sh /etc/conf.d/system-tar-and-restore.conf` will do the trick

or make it an alias in your .bashrc..?

**Comment by Petross404** [comment]
Of course 👍

**Comment by tritonas00** [comment]
Feel free to close the issue

**Comment by Petross404** [comment]
Thank you for your support :)
