### ISSUE TITLE
Should I boot from the liveCD?

### ISSUE THREAD

**Issue by 4qv907rtet5r** [tritonas00/system-tar-and-restore#13]
I'm going to backup my ubuntu 14.04
Should I boot from the liveCD?
Or is it ok to boot from ubuntu 14.04?

/var/log/syslog doesn't working

`-rw-r-----  1 sshd       adm        363401 Apr 27 14:08 syslog`
`# chown syslog:adm syslog* (works fine after this command)`
`-rw-r-----  1 syslog     adm        363862 May 10 17:17 syslog`

why changed ownership?

**Comment by tritonas00** [comment]
No, boot the system you want to backup

Ude livecd for restore mode

**Comment by 4qv907rtet5r** [comment]
how to prevent changing ownership when backup mode?

**Comment by tritonas00** [comment]
please be more specific

what exactly you did?

**Comment by 4qv907rtet5r** [comment]
yes. **restored system**'s some directory ownership changed.

`./star.sh -i 0 -d /root/backup/ -c none -u "-p --exclude=/root/backup/* --warning=none"`

`./star.sh -i 1 -r /dev/sdb1 -s /dev/sdb2 -G /dev/sdb -f /home/backup/backup.tar.gz` -u '-p'

**Comment by 4qv907rtet5r** [comment]
I apologize for my hasty behavior.
I've fixed the issue.

problem:
https://serverfault.com/a/440090

solution:
https://help.ubuntu.com/community/BackupYourSystem/TAR#Restoring

`-p --numeric-owner` option is required.

**Comment by tritonas00** [comment]
maybe the `--numeric-owner` solved the issue, because `-p` is already added by the script in both backup mode: https://github.com/tritonas00/system-tar-and-restore/blob/master/star.sh#L587
and restore mode: https://github.com/tritonas00/system-tar-and-restore/blob/master/star.sh#L822

Anyway, closing, thanks for the feedback.
