### ISSUE TITLE
Parallel Decompression

### ISSUE THREAD

**Issue by 0rinsb3lt** [tritonas00/system-tar-and-restore#14]
Noticed that on restoring a system that there was a significant amount of time checking the archive
and wondered if it could be quicker with parallel decompression. I know that pbzip2 has it.

tar supports a -I option to use other programs such as pbzip2
- tar -I pbzip2

possibly just reuse the -M --multi-core option for defining decompression (Restore mode).

**Comment by tritonas00** [comment]
> possibly just reuse the -M --multi-core option for defining decompression (Restore mode).

Yes, it's possible, i will look into it when i have my laptop back

**Comment by 0rinsb3lt** [comment]
I took your suggestion with the `"$BRreadopts"` and here is what I came up with
[diff.txt](https://github.com/tritonas00/system-tar-and-restore/files/2008746/diff.txt)

as for the -d from what I read is that when passing a program via -I the program itself simply has to support the -d option

https://linux.die.net/man/1/tar

**Comment by tritonas00** [comment]
yes like that but the statement must be before https://github.com/tritonas00/system-tar-and-restore/blob/master/star.sh#L764 not after

when i have my laptop i will extend it to all compressors and add threads also

**Comment by tritonas00** [comment]
> The diff shows that After 763 in the first file (original file) it's adding the lines from the second file (one I modified). That would put them above line 764.

you are right, i didn't watch carefully

>Other than that I think it paves the way for other compressors. ( I have another modification that adds pixz support)

exactly, but please check if non parallel way still works

**Comment by 0rinsb3lt** [comment]
can confirm that without -M option bzip2 is used. With -M option pbzip2 is used.

**Comment by tritonas00** [comment]
pbzip2 decompression is now done and you can use -z as well to define max threads

any idea of parallel decompressors for xz and gzip also?
