### ISSUE TITLE
home directory is not backed up completely

### ISSUE THREAD

**Issue by HardResetSolution** [tritonas00/system-tar-and-restore#17]
When using star.sh with the following arguments:

#./star.sh -i 0 -d /media/bralle/Backup

the resulting tar file contains an incomplete home directory.

content of original home directory:

#################################################

root@powertower:/home/bralle# ls -la
insgesamt 39368
drwxr-xr-x 35 bralle bralle      4096 Sep 11 21:05 .
drwxr-xr-x  3 root   root        4096 Mai 27 20:53 ..
drwxr-xr-x  2 bralle bralle      4096 Jul  6 18:53 .android
drwxr-xr-x  4 bralle bralle      4096 Jul  6 18:53 .AndroidStudio3.1
drwxr-xr-x  4 bralle bralle      4096 Mai 31 23:31 .audacity-data
-rw-------  1 bralle bralle      1425 Sep 10 23:43 .bash_history
-rw-r--r--  1 bralle bralle       220 Mai 27 20:53 .bash_logout
-rw-r--r--  1 bralle bralle      3526 Mai 27 20:53 .bashrc
drwxr-xr-x  2 bralle bralle      4096 Aug 27 20:01 Bilder
drwx------ 28 bralle bralle      4096 Sep 10 23:31 .cache
drwx------ 32 bralle bralle      4096 Aug 27 20:00 .config
-rw-------  1 bralle bralle 150691840 Aug 11 23:22 core
drwx------  3 bralle bralle      4096 Jun  9 10:24 .dbus
drwxr-xr-x  2 bralle bralle      4096 Mai 27 21:19 Dokumente
drwxr-xr-x 13 bralle bralle      4096 Sep 11 20:54 Downloads
drwx------  3 bralle bralle      4096 Jun 23 14:51 .gconf
drwxr-xr-x 24 bralle bralle      4096 Jun  9 10:24 .gimp-2.8
drwx------  3 bralle bralle      4096 Aug 20 22:26 .gnome
drwx------  3 bralle bralle      4096 Mai 27 21:20 .gnupg
drwxr-xr-x  2 bralle bralle      4096 Jul  2 22:43 .gphoto
-rw-------  1 bralle bralle     49086 Sep 11 18:59 .ICEauthority
-rw-rw-r--  1 bralle bralle        74 Jun  9 12:15 .install4j
drwxr-xr-x  4 bralle bralle      4096 Mai 28 21:08 .java
drwxr-xr-x 17 bralle bralle      4096 Aug 11 13:12 jd2
drwx------  3 bralle bralle      4096 Mai 27 21:19 .local
drwxr-xr-x  2 bralle bralle      4096 Jun 23 14:52 .MakeMKV
drwx------  5 bralle bralle      4096 Mai 28 21:01 .mozilla
drwxr-xr-x  2 bralle bralle      4096 Mai 27 21:19 Musik
drwxr-xr-x  2 bralle bralle      4096 Mai 27 21:19 Öffentlich
drwxr-xr-x  2 bralle bralle      4096 Aug 21 21:03 opt
drwxr-xr-x  2 bralle bralle      4096 Jun 23 12:39 .oracle_jre_usage
drwx------  3 bralle bralle      4096 Mai 29 21:13 .pki
drwxr-xr-x 11 bralle bralle      4096 Jun  3 17:49 .PlayOnLinux
drwx------  2 bralle bralle      4096 Jun  9 10:24 .presage
-rw-r--r--  1 bralle bralle       675 Mai 27 20:53 .profile
drwx------  3 bralle bralle      4096 Jul 11 00:40 .putty
drwxr-xr-x  3 bralle bralle      4096 Jun  3 17:01 .pyrenamer
drwxr-xr-x  2 bralle bralle      4096 Aug 28 17:53 Schreibtisch
drwx------  2 bralle bralle      4096 Mai 27 21:20 .ssh
drwx------  4 bralle bralle      4096 Jun  9 13:48 .thunderbird
drwxr-xr-x  2 bralle bralle      4096 Jun 24 15:36 Videos
drwxr-xr-x  2 bralle bralle      4096 Mai 27 21:19 Vorlagen
-rw-r--r--  1 bralle bralle       134 Jul  9 22:18 .xinputrc

#################################################

the content of the resulting tar file's home directory is only:

#################################################
.AndroidStudio3.1
.gconf
.gphoto
.pki
Bilder
Vorlagen
core
#################################################

log:

#################################################
System Tar & Restore 6.9

[SUMMARY]
ARCHIVE
/media/bralle/Backup/Backup-2018-09-11/Backup-pc-20180911-201742.tar.gz (/) 

ARCHIVER OPTIONS
--sparse
--acls
--xattrs
--exclude=/run/*
--exclude=/dev/*
--exclude=/sys/*
--exclude=/tmp/*
--exclude=/mnt/*
--exclude=/proc/*
--exclude=/media/*
--exclude=/var/run/*
--exclude=/var/lock/*
--exclude=.gvfs
--exclude=lost+found
--exclude=Backup-2018-09-11

HOME DIRECTORY
Include

FOUND BOOTLOADERS
Grub
EFISTUB/efibootmgr
Systemd/bootctl

[ARCHIVER]
tar: Entferne führende „/“ von Elementnamen
tar: /var/lib/samba/private/msg.sock/1209: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1308: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1371: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1129: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1319: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/19305: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1475: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1163: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1267: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1469: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1320: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1090: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1271: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1368: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1485: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1294: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/23918: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1386: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1240: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1444: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1425: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1172: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1303: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/930: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1120: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1154: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1340: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1312: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1311: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1351: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1313: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1452: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1403: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/3360: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1227: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1140: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1276: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1413: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1167: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1295: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1419: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1304: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1408: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1343: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/28064: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1493: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1348: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/7617: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1429: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1372: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1162: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1264: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/7616: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/19306: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1297: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1173: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1370: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1383: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1511: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1396: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1470: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1503: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1369: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1336: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1333: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1496: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1089: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1241: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1509: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1136: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1502: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1007: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1321: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1226: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1432: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1380: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1329: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1306: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1217: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1357: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/3359: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1430: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1274: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1433: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1268: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1504: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1245: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/2804: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1328: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1376: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1266: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1291: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1335: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1389: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1299: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1354: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1427: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1216: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1102: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1013: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1443: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1130: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1202: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1272: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1334: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1122: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1171: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1288: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1141: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1012: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/940: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1407: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1457: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1281: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1345: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1190: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1492: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1076: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/3325: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1480: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1235: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1416: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1474: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1406: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1301: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1484: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/967: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/23919: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1187: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1203: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1322: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1398: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1077: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1468: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/2614: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1198: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1176: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1210: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1186: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1495: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1456: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1185: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1326: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1072: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/23957: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1397: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1247: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1188: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1252: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/965: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1525: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1315: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1400: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1236: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1064: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1278: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/916: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1524: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1143: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1008: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1251: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1358: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1346: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1434: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1270: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1121: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1476: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1184: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1381: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1453: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1286: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1193: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/2805: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1071: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/19344: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1367: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/28024: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1279: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/10894: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/28023: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1285: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1455: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1399: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1204: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1151: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/966: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1390: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1325: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1428: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1375: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1418: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1414: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1382: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1309: Socket ignoriert
tar: /var/lib/samba/private/msg.sock/1445: Socket ignoriert
tar: Entferne führende „/“ von Zielen harter Verknüpfungen
tar: sys: Warnung: Funktion fgetxattr fehlgeschlagen: Die Operation wird nicht unterstützt
tar: sys: Warnung: Funktion fgetxattr fehlgeschlagen: Die Operation wird nicht unterstützt
409249 Files archived successfully
Elapsed time: 0 hours 14 min 1 sec

#################################################

**Comment by tritonas00** [comment]
what is the output of:

`tar tfz /media/bralle/Backup/Backup-2018-09-11/Backup-pc-20180911-201742.tar.gz | grep home`

**Comment by HardResetSolution** [comment]
Ah I see... star.sh is doing right.
With your command the "missing files" are listed.
It must have something to do with gnome archive manager, which does not list all files.
