### ISSUE TITLE
Somewhat difficult now to restore properly???

### ISSUE THREAD

**Issue by JoelParke** [tritonas00/system-tar-and-restore#19]

**Comment by tritonas00** [comment]
please describe your issue

**Comment by JoelParke** [comment]
Since Ubuntu 17.04, the option to reinstall has been removed.  
This week was the first time I needed to restore a backup since 17.04.
So I did a clean standard install of Ubuntu 18.04 and then:
sudo ./star.sh -i 1 -e /dev/sda1 -P xxx -r /dev/sda2 -G auto -l /boot/efi -f xxxx.tar.gz.aes

When I rebooted, the first kernel crashed immediately on boot.
The next boot the previous kernel booted.
I then discovered that the package system had some issues and I had to install a couple of packages.
And then doing an update and upgrade.
But I did discover that I could not run the 'Startup Disk Creator' - with an error in the udisks.
So now I will probably need to upgrade to Ubuntu 18.10.

SO my question:
Is there any way to record the versions of the installed packages with the backup?
So that one could install all those packages and versions?
Or perhaps there is a better option that I can't think of?

**Comment by tritonas00** [comment]
so you booted from 18.04 and restored a 17.04 backup?

**Comment by JoelParke** [comment]
I installed 18.04 standard.
I then updated.
I then restored the backup.
I then had the issues I reported.
Thanks.

**Comment by JoelParke** [comment]
When I did the restore in all cases:
I booted into 18.04 from a usb.
I then did the restore.
Sorry if I didn't make this clear.

**Comment by tritonas00** [comment]
And the backup is 18.04 updated? When you took the backup?

**Comment by JoelParke** [comment]
Yes.  Also, I believe I probably had a misunderstanding.  I assumed that I needed to install the same packages that were part of the system when the backup was made.  But I seem to have the best luck by just installing the standard Ubuntu 18.04 without any updates, other than the standard updates that happen during the standard install.  And then install a backup of Ubuntu 18.04 with all my settings, etc.  

One weirdness was that when I tried to upgrade to 18.10 after this, the desktop failed to show up on reboot.   But I only tried this once, and the same system failed to run 'Startup Disk Creator'.  My most recent test of clean install of Ubuntu 18.04 and then a restore, does run 'Startup Disk Creator', so go figure.  

? Are there any issues with permissions after the restore to 18.04 ?  

Thanks very much for a greate backup and restore package.  
Joel Parke

**Comment by tritonas00** [comment]
i will check backup/restore 18.04 in vbox next week

Backup mode restores a backup archive
Transfer mode transfers the current /

**Comment by tritonas00** [comment]
I reproduced the issue with 18.04. The problem seems to be tar, because Transfer Mode (rsync) works as expected.

I will try to fix it.

**Update**

It seems while i was doing the backup ubuntu did some background work which resulted in corrupted archive. I did another backup and then Restore worked fine. So before you start the backup make sure the system is idle and you have enough free space in the destination directory.

Feel free to re-open the issue if you experience it again and please post **backup.log** and **restore.log**

**Comment by JoelParke** [comment]
Thanks very much for checking on this.  I too have been able to reinstall and remove my issues.  Thanks for the suggestion to ensure that system is idle!!!  Free space was not an issue.
