### ISSUE TITLE
Support Multi-core Compression with pigz and pbzip2

### ISSUE THREAD

**Issue by art1fa** [tritonas00/system-tar-and-restore#2]
It would be nice to have multi-core support implemented while backing up the system.
Using pigz as compression program for gzip, I saved around half of the time.

Thank you very much for the script, I appreciate your work a lot.

**Comment by tritonas00** [comment]
I added the -m (--multi-core) argument which enables pigz or pbzip2 compressors in gzip and bzip2 automatically.

Can you give it a try?

**Comment by tritonas00** [comment]
Implemented in [4.9.2](https://github.com/tritonas00/system-tar-and-restore/releases/tag/4.9.2)
