### ISSUE TITLE
Is target dir auto excluded ?

### ISSUE THREAD

**Issue by frenzymind** [tritonas00/system-tar-and-restore#20]
Hello!
When I specify -d parameter, this directory is auto excluded from target archive ?

**Comment by frenzymind** [comment]
Hello!
When I specify -d parameter, this directory is auto excluded from target archive ?

**Comment by tritonas00** [comment]
No, only the directory containing the backup file, under the destination is auto excluded

**Comment by frenzymind** [comment]
Thank you for reply!
