### ISSUE TITLE
Error while trying to backup using livecd

### ISSUE THREAD

**Issue by beelesnik** [tritonas00/system-tar-and-restore#22]
Hello.
First of all thank You to this utility.
When I made back up from working system all works well. To restore I used Live CD Antix and again all works well. 

Is there any possibility to make backup on offline system using Live CD?
To make backup I booted from live USB with Antix linux (with additional data partition for storing archives). Then mount needed root fs of my system  to /mnt/source and made backup:
`star.sh -i 0 -jq -c gzip -d "/mnt/archive" -n "Backup-20191114-005040" -T "/mnt/source" -g`
Log after backup is that:
```
[SUMMARY]
ARCHIVE
/mnt/archive/Backup-2019-11-14/Backup-20191114-005040.tar.gz (/mnt/source)

ARCHIVER OPTIONS
--exclude=Backup-2019-11-14

[ARCHIVER]
tar: source/tmp/.X11-unix/X0: socket ignored
75427 Files archived successfully
Elapsed time: 0 hours 9 min 39 sec

[CONFIGURATION FILE]
# Auto-generated configuration file for backup mode. Place it in /etc

BRdestination="/mnt/archive"
BRcompression="gzip"
BRname="Backup-20191114-005040"
BRnocolor="Yes"
BRquiet="Yes"
BRsrc="/mnt/source"
```

I see that gzip file of backup has one level that I do not need:
```
root@antix1:/mnt/archive/system-tar-and-restore-master# tar -tf ../Backup-2019-11-14/Backup-20191114-005040.tar.gz  | head -n 4
source/
source/home/
source/home/proof/
source/home/proof/.lesshst
root@antix1:/mnt/archive/system-tar-and-restore-master#
```

Next I tried to make restore and always got an error like this
` Running and target system architecture mismatch or invalid archive`

For example (standard options):
```
root@antix1:/mnt/archive/system-tar-and-restore-master# ./star-gui.sh
star.sh -i 1 -jq -f "/mnt/archive/Backup-2019-11-14/Backup-20191114-005040.tar.gz" -r /dev/sda1 -s /dev/sda5 -G /dev/sda
System Tar & Restore 7.0
Checking archive type

[MOUNTING]
Making working directory
Mounting /dev/sda1

[BACKUP ARCHIVE]
Checking and reading archive (75427 Files)

[CLEANING AND UNMOUNTING]
Unmounting /dev/sda1
root@antix1:/mnt/archive/system-tar-and-restore-master#
```

I used the  --strip-components=NUMBER as additional options for tar to remove one level in the path of backed archive:
```
root@antix1:/mnt/archive/system-tar-and-restore-master# ./star-gui.sh
star.sh -i 1 -jq -f "/mnt/archive/Backup-2019-11-14/Backup-20191114-005040.tar.gz" -u "--strip-components=1" -r /dev/sda1 -s /dev/sda5 -G /dev/sda
System Tar & Restore 7.0
Checking archive type

[MOUNTING]
Making working directory
Mounting /dev/sda1

[BACKUP ARCHIVE]
Checking and reading archive (75427 Files)

[CLEANING AND UNMOUNTING]
Unmounting /dev/sda1
root@antix1:/mnt/archive/system-tar-and-restore-master#
```

And with override flag:
```
root@antix1:/mnt/archive/system-tar-and-restore-master# ./star-gui.sh
star.sh -i 1 -jq -f "/mnt/archive/Backup-2019-11-14/Backup-20191114-005040.tar.gz" -u "--strip-components=1" -r /dev/sda1 -s /dev/sda5 -G /dev/sda -o
System Tar & Restore 7.0
Checking archive type

[MOUNTING]
Making working directory
Mounting /dev/sda1

[BACKUP ARCHIVE]
Checking and reading archive (75427 Files)

[CLEANING AND UNMOUNTING]
Unmounting /dev/sda1
root@antix1:/mnt/archive/system-tar-and-restore-master#
```

What should I do to execute backup and restore operations from Live CD?
Thank You

**Comment by tritonas00** [comment]
> Is there any possibility to make backup on offline system using Live CD?

not supported, sorry

changing the source dir (-T), the script will just backup and not create a restorable archive via restore mode

you need to chroot in that system you mounted (/mnt/source) and then backup normally

**Comment by beelesnik** [comment]
Thank You again for quick answer
