### ISSUE TITLE
Could You describe --destination option for backup

### ISSUE THREAD

**Issue by beelesnik** [tritonas00/system-tar-and-restore#23]
Hello.
Just simple question.
When I made backup like this:
`bin/bash star.sh -i 0 -jq -c gzip -d "/mnt/dest/backup" -n "brickbackup" -T "/"`
I got that final backup was located in:
```
 ls -al /mnt/dest/backup/Backup-2019-11-15
total 921992
drwxrwxrwx 2 root root      4096 Nov 15 03:35 .
drwxr-xr-x 3 root root      4096 Nov 15 03:35 ..
-rw-rw-rw- 1 root root       613 Nov 15 03:44 backup.log
-rw-rw-rw- 1 root root 944100431 Nov 15 03:44 brickbackup.tar.gz
```
How could I create fixed destination path for backup? I mean that if I use options
` -d "/mnt/dest/backup" -n "brickbackup"`
I get path for created backup indeed:
`/mnt/dest/backup/brickbackup.tar.gz`

**Comment by tritonas00** [comment]
not possible, the `Backup-YYYY-MM-DD` dir is created by the script inside the destination

**Comment by beelesnik** [comment]
Thanks
