### ISSUE TITLE
Best script ever

### ISSUE THREAD

**Issue by 7e4** [tritonas00/system-tar-and-restore#25]
Thanks a lot for sharing this code, saved me countless hours of doing stuff manually!

**Comment by tritonas00** [comment]
Hi. Its a bit dated now. Backup mode works, i use it from time to time on Arch, restore/transfer mode though, havent test for a long time

**Comment by 7e4** [comment]
works like a charm on raspberry, debian buster, debian sid :) all i need. when it breaks, probably need to change some stuff in star.sh but for now it works flawless.. love it ;)
