### ISSUE TITLE
Date format in default file name causes tar error

### ISSUE THREAD

**Issue by art1fa** [tritonas00/system-tar-and-restore#3]
Trying to open the archive with the default file name `Backup-$(hostname)-$(date +%Y-%m-%d-%T)` with `tar -ztvf backup.tar.gz` results in the error

>tar (child): Cannot connect to Backup-localhost-19-07-2015-20: resolve failed
>gzip: stdin: unexpected end of file
>tar: Child returned status 128
>tar: Error is not recoverable: exiting now`

After searching the internet, I ran across the following line from the GNU Tar documentation:

>If the archive file name includes a colon (`:'), then it is assumed to be a file on another machine.

So basically the colon in the time format causes the error. This could be easily fixed by setting a slightly different default file name for backups, e.g. with `$(date +%Y-%m-%d__%H_%M)` as the date variable.

**Comment by tritonas00** [comment]
Well, restore.sh uses another syntax (see run_tar)

You can use `-f $(date +%Y-%m-%d__%H_%M)` or specify it in backup.conf: 
>BRNAME="$(date +%Y-%m-%d__%H_%M)"

If this really is a problem, i will change it to something like `$(date +%Y-%m-%d-%H_%M_%S)` :)

**Comment by art1fa** [comment]
Yes, I know I can specify the filename in the backup.conf file which I already did ;) 
Just wanted to let you know, because I often check the contents of the archive after backup without actually restoring it. Thanks though for your amazing work!

**Comment by tritonas00** [comment]
Well i just tried

`tar -ztvf  /tmp/Backup-2015-09-19/Backup-Desktop-2015-09-19-18:51:51.tar.gz`

and worked fine here. I am on Arch with tar 1.28
