### ISSUE TITLE
system-tar-and-restore failed on rhel5 and rhel6?

### ISSUE THREAD

**Issue by JohnnyRad** [tritonas00/system-tar-and-restore#4]
I know system-tar-and-restore Supported distributions: Arch, Debian/Ubuntu, Fedora, openSUSE, Gentoo, Mandriva/Mageia,

I want to backup a rhel5-x86-64 server, system-tar-and-restore found that bootloaders is Syslinux, but real bootloader is Grub Legacy0.97.
I could backup the rhel5-x86-64 server in "CLI" mode, but when i restore, system-tar-and-restore failed, seems like system-tar-and-restore couldn't found the real bootloader.

then how can i do?

**Comment by tritonas00** [comment]
Hi. The project doesn't support Grub Legacy, only Grub 2.

**Comment by JohnnyRad** [comment]
I want to restore the backup.tar.gz to a new disk, 
can I uncompress the backup.tar.gz manually to a new disk and then setup Grub Legacy?
i

**Comment by JohnnyRad** [comment]
can I boot into linux rescue mode ,  mount two disk to /mnt/sda and /mnt/sdb(new disk), then chroot /mnt/sdb, and then uncompress backup.tar.gz?

**Comment by tritonas00** [comment]
start the restore.sh script and **don't** choose a bootloader.

at the end, the script will tell you what to do (chroot and install grub)

**Comment by JohnnyRad** [comment]
@tritonas00 thanks. I will test it soon.

**Comment by JohnnyRad** [comment]
Enter the path of the backup file
Path: /Backup-2016-07-26/rhel5.8-64.tar.gz
Checking archive type...
Checking and reading archive (101949 Files) 

::SUMMARY
TARGET PARTITION SCHEME:
Partition   Mountpoint  Filesystem  Size              Options
/dev/sdb1   /           ext3        defaults,noatime

BOOTLOADER:
None (WARNING)

PROCESS:
Mode:     Restore
Archive:  gzip compressed 
System:   Fedora based x86_64

ARCHIVER OPTIONS:
--selinux
--acls
--xattrs-include='*'

Continue?
(Y/n):Y

::PROCESSING


::GENERATING FSTAB
cp: cannot stat `/mnt/target/etc/fstab': No such file or directory
./restore.sh: line 2251: /mnt/target/etc/fstab: No such file or directory
cat: /mnt/target/etc/fstab: No such file or directory
ls: /mnt/target/boot/: No such file or directory

Edit fstab?
(y/N):N

::PREPARING CHROOT ENVIRONMENT
Binding /run
mount: mount point /mnt/target/run does not exist
Binding /dev
mount: mount point /mnt/target/dev does not exist
Binding /dev/pts
mount: mount point /mnt/target/dev/pts does not exist
Binding /proc
mount: mount point /mnt/target/proc does not exist
Binding /sys
mount: mount point /mnt/target/sys does not exist

::REBUILDING INITRAMFS IMAGES
grep: /mnt/target/etc/fstab: No such file or directory

Completed. Log: /tmp/restore.log

You didn't choose a bootloader, so this is the right time to install and
update one. To do so:

==>For internet connection to work, on a new terminal with root
   access enter: cp -L /etc/resolv.conf /mnt/target/etc/resolv.conf

==>Then chroot into the target system: chroot /mnt/target

==>Install and update a bootloader

==>When done, leave chroot: exit

==>Finally, return to this window and press ENTER to unmount
   all remaining (engaged) devices.
   
till here, I opened a new terminal,and run chroot;
   
   [root@localhost system-tar-and-restore-5.2]# chroot /mnt/target/
chroot: cannot run command `/bin/bash': No such file or directory

because /mnt/target directory is empty, I cannot change root directory.

so I uncompressed the  rhel5.8-64.tar.gz to /mnt/target manually, 

but I coundn't install grub:
[root@localhost /]# grub-install /dev/sda
/dev/sda: Not found or not a block device.
[root@localhost /]# grub-install /dev/sda1
/dev/sda1: Not found or not a block device.
[root@localhost /]# grub-install --root-directory=/boot /dev/sda1
Probing devices to guess BIOS drives. This may take a long time.
No suitable drive was found in the generated device map.
[root@localhost /]# df -hT
Filesystem    Type    Size  Used Avail Use% Mounted on
/dev/sda2     ext3     42G  2.6G   37G   7% /
sysfs        sysfs     42G  2.6G   37G   7% /sys
df: `/dev/pts': No such file or directory
/dev/sda1     ext3     42G  2.6G   37G   7% /boot
df: `/dev/shm': No such file or directory
df: `/proc/sys/fs/binfmt_misc': No such file or directory
df: `/proc/fs/vmblock/mountPoint': No such file or directory
sunrpc  rpc_pipefs     42G  2.6G   37G   7% /var/lib/nfs/rpc_pipefs

when I reboot the system, Grub cannot find file:

![rhel5 8-x64](https://cloud.githubusercontent.com/assets/8325079/17141682/a57aa2fa-537f-11e6-8c5e-71651d9f73a8.png)

**Comment by tritonas00** [comment]
Can you retry and post **/tmp/restore.log** here after please?

Thanks.

**Comment by JohnnyRad** [comment]
[root@localhost ~]# cat /tmp/restore.log 
====================System Tar & Restore 5.2 {2016-07-26-07:12:10}====================

::SUMMARY
TARGET PARTITION SCHEME:
Partition   Mountpoint  Filesystem  Size              Options
/dev/sdb1   /           ext3        defaults,noatime

BOOTLOADER:
None (WARNING)

PROCESS:
Mode:     Restore
Archive:  gzip compressed 
System:   Fedora based x86_64

ARCHIVER OPTIONS:
--selinux
--acls
--xattrs-include='*'

::TAR/RSYNC STATUS
tar: unrecognized option `--xattrs-include='*''
Try `tar --help' or `tar --usage' for more information.

::PREPARING CHROOT ENVIRONMENT
Binding /run
mount: mount point /mnt/target/run does not exist
Binding /dev
mount: mount point /mnt/target/dev does not exist
Binding /dev/pts
mount: mount point /mnt/target/dev/pts does not exist
Binding /proc
mount: mount point /mnt/target/proc does not exist
Binding /sys
mount: mount point /mnt/target/sys does not exist

::REBUILDING INITRAMFS IMAGES
grep: /mnt/target/etc/fstab: No such file or directory

**Comment by tritonas00** [comment]
so thats the problem: `tar: unrecognized option --xattrs-include='*''`

please open **restore.sh** with a text editor, go to that line https://github.com/tritonas00/system-tar-and-restore/blob/master/restore.sh#L184

and replace `"--xattrs-include='*'"` with `--xattrs`, save and retry.

**Comment by JohnnyRad** [comment]
Thanks @warlock90 
Ok,  will test it .

**Comment by JohnnyRad** [comment]
@tritonas00 
Great, till here is right (I didn't select bootloader. ):

You didn't choose a bootloader, so this is the right time to install and
update one. To do so:

==>For internet connection to work, on a new terminal with root
   access enter: cp -L /etc/resolv.conf /mnt/target/etc/resolv.conf

==>Then chroot into the target system: chroot /mnt/target

==>Install and update a bootloader

==>When done, leave chroot: exit

==>Finally, return to this window and press ENTER to unmount
   all remaining (engaged) devices.

I have a question:
which device should I setup the grub into?

here is my disk info:
**before the command chroot /mnt/target:**
[root@localhost ~]# df -hT
Filesystem    Type    Size  Used Avail Use% Mounted on
/dev/sda2     ext3     37G  3.3G   32G  10% /
/dev/sda1     ext3    289M   17M  258M   6% /boot
tmpfs        tmpfs    499M     0  499M   0% /dev/shm
/dev/sdb1     ext3     42G  2.6G   37G   7% /mnt/target
[root@localhost ~]# fdisk -l

Disk /dev/sda: 42.9 GB, 42949672960 bytes
255 heads, 63 sectors/track, 5221 cylinders
Units = cylinders of 16065 * 512 = 8225280 bytes

   Device Boot      Start         End      Blocks   Id  System
/dev/sda1   *           1          38      305203+  83  Linux
/dev/sda2              39        4964    39568095   83  Linux
/dev/sda3            4965        5221     2064352+  82  Linux swap / Solaris

Disk /dev/sdb: 64.4 GB, 64424509440 bytes
255 heads, 63 sectors/track, 7832 cylinders
Units = cylinders of 16065 * 512 = 8225280 bytes

   Device Boot      Start         End      Blocks   Id  System
/dev/sdb1   *           1        5472    43953808+  83  Linux

**after run the command #chroot /mnt/target:**
[root@localhost /]# df -hT
Filesystem    Type    Size  Used Avail Use% Mounted on
/dev/sda2     ext3     42G  2.6G   37G   7% /
/dev/sda1     ext3     42G  2.6G   37G   7% /boot
tmpfs        tmpfs    499M  124K  499M   1% /dev/shm
sunrpc  rpc_pipefs     42G  2.6G   37G   7% /var/lib/nfs/rpc_pipefs

**Comment by tritonas00** [comment]
the one that shows in the chroot enviroment i suppose

**Comment by JohnnyRad** [comment]
@tritonas00 
**after run the command #chroot /mnt/target:**
[root@localhost /]# grub-install /dev/sda
The file /boot/grub/stage2 not read correctly.
[root@localhost /]# grub-install /dev/sda1
The file /boot/grub/stage2 not read correctly.

[root@localhost /]# grub-install /dev/sdb
/dev/sdb does not have any corresponding BIOS drive.
[root@localhost /]# grub-install /dev/sdb1
/dev/sdb1 does not have any corresponding BIOS drive.

is my way right to Install and update a bootloader?

**Comment by tritonas00** [comment]
try grub-install --recheck /dev/sdb

**Comment by JohnnyRad** [comment]
[root@localhost /]# grub-install --recheck /dev/sdb
Probing devices to guess BIOS drives. This may take a long time.
The file /boot/grub/stage2 not read correctly.

after run the command #chroot /mnt/target:
the system cannot identify /dev/sdb.

**leave chroot: exit**
[root@localhost ~]# grub-install --recheck /dev/sdb
Probing devices to guess BIOS drives. This may take a long time.
Installation finished. No error reported.
This is the contents of the device map /boot/grub/device.map.
Check if this is correct or not. If any of the lines is incorrect,
fix it and re-run the script `grub-install'.

(fd0)	/dev/fd0
(hd0)	/dev/sda       (old disk)
(hd1)	/dev/sdb      (new disk)

**Comment by tritonas00** [comment]
well this might work but the boot files are in the old disk this way.

i don't have experience with grub legacy, sorry.

Your distro doesn't support grub2?

**Comment by JohnnyRad** [comment]
When I reboot , the system says "Grub Hard Disk error",  bootloader problem too.

@tritonas00 
My system is rhel5.8 x84-64, doesn't support Grub2.

**Comment by tritonas00** [comment]
Oh, thats too old.

Maybe you want to give syslinux a try.

If you want to retry with grub and don't want to re-run restore.sh:

mkdir /mnt/target
mount /dev/sdb1 /mnt/target
mount --bind /run /mnt/target/run
mount --bind /dev /mnt/target/dev
mount --bind /dev/pts /mnt/target/dev/pts
mount --bind /proc /mnt/target/proc
mount --bind /sys /mnt/target/sys

chroot /mnt/target
install and update grub

umount /mnt/target/dev/pts
umount /mnt/target/proc
umount /mnt/target/dev
umount /mnt/target/sys
umount /mnt/target/run
umount /dev/sdb1

reboot

**Comment by JohnnyRad** [comment]
@tritonas00 
Thanks a lot! I will try it.

**Comment by JohnnyRad** [comment]
test to install grub2 to boot the system;  
says:
error: no such device : some number for UUID
Entering rescue mode...
grub rescue>

**Comment by tritonas00** [comment]
you did `grub2-mkconfig -o /boot/grub2/grub.cfg` in chroot after the the grub2-install ?

**Comment by JohnnyRad** [comment]
@tritonas00  no, should I do that ?
I just run grub-install /dev/sda.

**Comment by tritonas00** [comment]
yes.

**Comment by JohnnyRad** [comment]
In chroot, there is no grub2-mkconfig command in rhel5 system ;
but when I boot system in rhel7 rescue mode,  the rhel5 system can be mounted   , really surprise!
The rhel5 rescue mode could not find the system image previously.

![rhel7_x64-2016-07-28-21-46-23](https://cloud.githubusercontent.com/assets/8325079/17214935/bdb91646-550d-11e6-910a-01b1c973f733.png)
![rhel7_x64-2016-07-28-21-54-57](https://cloud.githubusercontent.com/assets/8325079/17214998/f94ecd68-550d-11e6-9ddc-958e4c190522.png)

**Comment by tritonas00** [comment]
try `grub-mkconfig -o /boot/grub2/grub.cfg`

**Comment by JohnnyRad** [comment]
@tritonas00 there is no grub-mkconfig command in chroot(rhel5);
should I install some rpms for that command? Now I can mount rhel5 iso .

![rhel7_x64-2016-07-28-22-15-54](https://cloud.githubusercontent.com/assets/8325079/17215855/e3dfc20e-5510-11e6-84e8-0e63e1d7316d.png)

**Comment by tritonas00** [comment]
grub-mkconfig is a part of grub2.

how did you installed grub2?

**Comment by JohnnyRad** [comment]
@tritonas00 , I have a rhel7 system, add a new disk to rhel7, then uncompress rhel5.tar.gz to the new disk, then boot into rhel7 rescue mode , at here I could install grub2 in the added new disk. But, also boot into grub rescue , 
Up to now, the problem is still not resolved.

**Comment by tritonas00** [comment]
you must install grub**2** in the rhel**5** system.
you have to chroot in rhel5 (from your rhel7 system), and install and update grub2 in there
 
if this is not possible. then you have to boot it from rhel7 grub2:

make sure you have os-prober installed and do `grub2-mkconfig -o /boot/grub2/grub.cfg` so it will find your rhel5 system and create an entry for it.

**Comment by JohnnyRad** [comment]
@tritonas00 Thanks! Thanks!Thanks!

The magic os-prober command found the rhel5.8, then grub2-mkconfig created then entry for rhel5.
Now I can boot into rhel5 system. Wow, GREAT!

Of course, there are some small problems, I couldn't open terminal, the eth0 down(maybe the Dual NIC problem), I think I will solve these problems.

Finally, Thanks you @tritonas00 .

**Comment by tritonas00** [comment]
Great.

A last question, you extracted the rhel5 system by hand or with the restore.sh script?

**Comment by JohnnyRad** [comment]
With the restore.sh script.
But  the way extract it by hand will also be effective, I think.

**Comment by tritonas00** [comment]
ok then.

if you do it by hand, you must also chroot and create new fstab and regenerate initramfs images for your kernel(s)

also now you can boot the rhel5 system, you can install grub legacy in there normally (if you want to boot it from it's new disk)

closing the issue now :+1:

**Comment by JohnnyRad** [comment]
@tritonas00 

![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)
