### ISSUE TITLE
Ubuntu 16.04: GUI wrapper can't find functions

### ISSUE THREAD

**Issue by lolo120916** [tritonas00/system-tar-and-restore#5]
OS: Ubuntu 16.04.1 Arch: Amd64 gtkdialog: 0.8.3

Gtkdialog windows can't call functions exported by star-gui.sh (scan_disks hide_used_parts set_default_pass set_default_opts set_default_multi set_args status_bar run_main).

One solution, as reported by the developer of multisystem (https://forum.ubuntu-fr.org/viewtopic.php?id=1987488), consists in putting functions in a separate script that can be sourced by gtkdialog at every function call. This does work.

This problem seems related specifically to Ubuntu 16.04. As I am not a shell expert, I have no clue about where it steams from.

**Comment by tritonas00** [comment]
Does it work in other ubuntu version?

**Comment by lolo120916** [comment]
Not tested myself directly. But according to the above mentioned thread, it seems that this type of  problem is not encountered in Ubuntu 14.04. For other versions, I have no idea. The author of multisystem evokes security patches, but without more details.

This is the only link related to this problem I have found when googling.

**Comment by tritonas00** [comment]
I installed ubuntu 16.04 Amd64 in vbox and i can reproduce the issue.

I dont think i can found a proper solution, as this is probably a distro configuration issue.

For now you can change your default shell to bash:

Run ` sudo dpkg-reconfigure dash `, choose <No> and logout.

This way you can run the gui wrapper fine.

**Comment by lolo120916** [comment]
Thanks for your answer and having taken the time to characterize the origin of the problem. 
Changing the default shell impacts system scripts speed. So I won't touch it. As you stated, there is no clean solution. So, I will live with the solution of moving the functions in a separate script, which works.

Many thanks for your very useful backup/restore scripts, and also very valuable as advanced shell scripting examples. Best regards.

**Comment by tritonas00** [comment]
Feel free to close the issue and please check out the upcoming version 6.0 https://github.com/tritonas00/system-tar-and-restore/tree/6.0

I will try to ask gtkdialog developer if a proper solution can be found.

**Comment by tritonas00** [comment]
@lolo120916  i think this https://github.com/tritonas00/system-tar-and-restore/commit/bd53ffa989183aaf8a0359ef6759c54542ecc47d fixes the issue

Please run `git clone https://github.com/tritonas00/system-tar-and-restore -b 6.0` and try

**Comment by lolo120916** [comment]
Yep, this also works. The principle remains the same, but it has the advantage of having a standalone script.
Once again, many thanks. I guess I can now close the issue :-).
