### ISSUE TITLE
system-tar-and-restore does not work with nvme SSD drive

### ISSUE THREAD

**Issue by scottbass** [tritonas00/system-tar-and-restore#6]
Sending this from work, not in front of my system, but hopefully my memory will suffice :)

star.sh did not work on my system which has an nvme SSD drive.  IIRC the backup worked ok but the restore failed.  I think it was complaining about not finding the boot partition (?).

Anyway, I grepped the script for the error msg, found the scan_part() and scan_disk() functions, and  patched the script.

The solution was to clone the appropriate lines with the regex: nvme[0-9]+n[0-9]+p[0-9]+

The extent of my code review was limited to those two functions, which enabled the script to work.

My SSD partitions are named /dev/nvme0n1p1, /dev/nvme0n1p2, etc.

Happy to send more details from home if you need more info.

Thanks for the great work, much appreciated! :+1:

**Comment by tritonas00** [comment]
Thanks for the feedback. I added the code https://github.com/tritonas00/system-tar-and-restore/commit/2f8190d5881ffc0f1b5c1a2e57a495af52f689bb

Can you try again please?

**Comment by tritonas00** [comment]
closing, confirmed here https://github.com/tritonas00/system-tar-and-restore/issues/7#issuecomment-283860956
