### ISSUE TITLE
Enhancement request: switch to wipe files from partition on restore

### ISSUE THREAD

**Issue by scottbass** [tritonas00/system-tar-and-restore#7]
Here is my use case:

I'm a Linux noob although experienced IT consultant with Unix experience.
I've chosen to start with Arch, struggling through as a means to learn more Linux skills.
I tend to break things later in the piece (DE/WM environments), and want to create restore points at key intervals to save time rather than completely reinstalling bits I've done 20-30 times already ;-)
system-tar-and-restore is fantastic because the CLI doesn't require a WM or DE, so I can use it on a minimal Arch install from the virtual console.

Now, as I understand it, to properly restore back to a point in time, I need to clear out the root and home partitions.  Otherwise there would be "left over" files that could conflict after restoring to an earlier date.

Also, I often have other partitions mounted:  
/backups is an external USB stick (where I send star.sh backups), 
/boot is my UEFI partition for dual-booting Windows, (wiping this would be a disaster)
/data is a partition for "data" (VMs, media, etc),  (wiping this would be a disaster)
/nfs contains a NFS share from my NAS.

After Googling a bit, this is the approach I'm using to clear out the old partitions:

```
umount -R /mnt  
ls /mnt  # should be empty

mount /dev/mapper/vg00-Root /mnt
mount /dev/mapper/vg00-Home /mnt/home

cd /mnt 
ls . home                           # home and other root directories should not be empty
ls boot backups data nfs  # boot, backups, data, and nfs should (must) be empty
                                 
find /mnt -mindepth 1 -delete    # wipes root and home partitions
```

If I have the wrong partitions accidentally mounted under root (/mnt), issuing this command could be disastrous.

I know about the -x switch, but AFAIK this will not clear out root, it merely allows the restore into a non-empty root partition.  

My request is a switch that would clear out root and optionally home, would do so in a "safe" manner (from someone smarter than a Linux noob), and would cleanly restore back to a point in time as per many commercial backup/restore applications (TimeMachine, etc, etc).

Perhaps something like:

dirs="bin etc sbin usr ..."
for d in dirs; do find /mnt/$d -mindepth 1 -delete; done  ???

Whatever will properly clear out root (as fast as possible) and optionally home, yet not clear out any non-standard mount points in case they were accidentally mounted.  Which they shouldn't be if star.sh is controlling the mounting of the partitions and the clearing out of old files.

Thanks for listening :)

**Comment by tritonas00** [comment]
> and want to create restore points at key intervals to save time

You should check btrfs subvolumes/snapshots :smile:

> rather than completely reinstalling bits

system-tar-and-restore it's just a tar/rsync wrapper with some housekeeping functions

It's purpose is to backup/restore/transfer an entire system (/) in different disk/partition layouts and machines.

If you want to restore an older backup just give to star.sh a target **formatted** root and /home partition :smile:

I could implement your idea (like: -r /dev/sda1* -h /dev/ sda2* and if it sees the * it can rm -r the corresponding device's contents after mounting it and before mounting the next target partition)
 
but what's the problem about formatting your target root and /home partitions before give them to star.sh?

**Comment by scottbass** [comment]
> You should check btrfs subvolumes/snapshots :smile:

Yep, maybe down the road, assuming it's a good file system for an SSD, well supported and mature, etc.  I wanted to use F2FS but encountered issues, so fell back to good old ext4.

I *am* using LVM...perhaps LVM snapshots would work as a backup/restore approach?  Will need to investigate further at some point.

Regardless, I'm drifting away from issues relevant to star :wink:

> It's purpose is to backup/restore/transfer an entire system (/)

Well it *does* accept --exclude directories, so I *could* do a partial backup/restore if desired.

> what's the problem about formatting your target root and /home partitions before give them to star.sh?

No problem at all.  I was reformatting the partitions:

`mkfs.ext4 /dev/mapper/vg00-Root`

but that changes the UUID, which messes up my /etc/fstab and grub config, which I don't want to re-edit after doing the restore.

I was just suggesting an enhancement that would move star closer to what I perceive as the functionality in other backup/restore applications, both Linux and other O/S's.

I suppose I can use star.sh as a "low level" backup/restore application, and a GUI backup/restore application once I have a DE installed.  [https://wiki.archlinux.org/index.php/Synchronization_and_backup_programs](url)  Where to start???

I *really* like star, but whatever approach saves me time on the backup/restore when I break things is what I want to use.  I was thinking this enhancement request would save me time for my use case, as well as making it safer esp. for an inexperienced Linux user.

Feel free to close this if you disagree that this would be useful and worth the development effort.

Thanks again for this great utility!!!

**Comment by tritonas00** [comment]
> Well it does accept --exclude directories

It actually accepts almost everything tar/rsync accepts, not only --exclude=

> but that changes the UUID, which messes up my /etc/fstab and grub config, which I don't want to re-edit after doing the restore.

Ah. now i see your point. I will see what can i do.

**Comment by tritonas00** [comment]
Implemented https://github.com/tritonas00/system-tar-and-restore/commit/2d7dca4af02d6ff8f070098e348c9668b39b2376 and tested :smile:
![2017-02-28-163212_1920x1080_scrot](https://cloud.githubusercontent.com/assets/2660424/23410425/e40c15c8-fdd7-11e6-9c26-ec7de3575a36.png)

No extra switch, just add a trailing @ in the partition you want the script to clean

e.g -r /dev/sda2@ -h /dev/sda3@

It is implemented globally so it works even with custom partitions 
(like -t "/var/=/dev/sda3@ /opt=/dev/sda4@"

**Be careful** with this feature!

**Comment by scottbass** [comment]
Hi, 

Just a quick message to say I _will_ get to testing this, but probably over the weekend.  I don't have a vbox setup yet.

Some general comments from light testing last night:

- I first tried "stupid noob" testing by trying a restore on my running system.  It was good to see that it wouldn't allow a restore on a mounted root partition.

(BTW, I assume that a backup is fine from the production environment, since any files locked are in the --exclude directories anyway?  I only need to boot into the Live CD if I need to do a restore/transfer?  If this is the case, perhaps clarify this in the examples in the README.MD?)

- I'll include testing designed to be "stupid" and break.  In particular, I'll mount partitions, eg. a junk USB stick or HDD, in a partition mounted under root (or under /mnt/), then wiping root.  Those external partitions should not get wiped.  I assume this will all work ok, since you manage the mounting of /root and /home (and others) (I think you mount to /mnt/target), so you start with a clean/known state before other processing.
- In my testing, I copied a backup.conf to /etc to read my stored options, but supplied command line options (-d for target backup directory).  I would expect command line options to override any options saved in backup.conf, but that didn't appear to be the case.
- Minor (and probably premature):  if you expect these changes to get through, consider updating the help and examples on the website.

I'll follow up with testing results once I get more time to conduct that testing.

**Comment by tritonas00** [comment]
Hi

> any files locked are in the --exclude directories anyway?

What do you mean by "locked" files? By default backup mode excludes those: https://github.com/tritonas00/system-tar-and-restore/blob/master/star.sh#L531-L542

> I only need to boot into the Live CD if I need to do a restore/transfer?

You need a livecd, or another system only for Restore Mode. Transfer Mode transfers a running system (/) just as Backup Mode backups a running system

> In particular, I'll mount partitions

No! You don't mount anything. The script mounts your defined partitions and creates the corresponding mountpoints (root under /mnt/target, optional /boot under /mnt/target/boot etc)

The script will not accept already mounted partitions!

> then wiping root

Again no! Let me give a example: Let say your target partitions are / (/dev/sda2) /boot (/dev/sda1) and /home (/dev/sda3), you excluded /boot in the backup because you want to to keep your current /boot partition unchanged, and you want the script to clean the target root and /home partitions contents before starts restoring. So:

star.sh -r /dev/sda2@ -h /dev/sda3@ -b /dev/sda1

Now the script will mount the target root partition first (under /mnt/target) and it will rm -r it's contents. Then it will mount the target /boot partition (which already contains files) under /mnt/target/boot and will not touch it(no trailing @), then it will mount the target /home partition /dev/sda3 under /mnt/target/home and again will rm -r it's contents. Then will start restoring the backup.

> would expect command line options to override any options saved in backup.conf, but that didn't appear to be the case

Yes i'm aware of this, only star-gui.sh does that (reads backup.conf but any changes you make in the gui will override the conf file)

Please, test to vbox to get familiar with star first :smile:

**Comment by scottbass** [comment]
> What do you mean by "locked" files? By default backup mode excludes those: https://github.com/tritonas00/system-tar-and-restore/blob/master/star.sh#L531-L542

What I meant by "locked" files are files (or virtual files) in /proc, /sys, /var, etc. that, in a running system, might prevent a valid backup by incorrectly copying the file.  "locked" is a term borrowed from Windows that perhaps is inappropriate to Linux.

> You need a livecd only for Restore Mode.

Thanks, if that was clear in the Readme I missed it and apologize.  So:

backup: can be done from a running system
restore: must be done from a Live CD
transfer: must be done from a running system, where such system is transferred to the partitions listed in the star invocation parameters.

> No! You don't mount anything. The script mounts your defined partitions and creates the corresponding mountpoints (root under /mnt/target, optional /boot under /mnt/target/boot etc)

Yes I know :)  I was *purposely* trying to be as stupid and "noobish" as possible to try and break the wipe functionality, such that a partition mounted under root would accidentally get wiped.  This new functionality, while useful, *is* dangerous, so I want to thoroughly test so the user don't shoot him/herself in the foot (or head) by losing data he wanted to keep.

> No! You don't mount anything. The script mounts your defined partitions and creates the corresponding mountpoints (root under /mnt/target, optional /boot under /mnt/target/boot etc)

Great!!!  That's what I wanted to hear ;)  So this would unmount any partitions mounted under root, then re-mounts root (and home, boot, et. al.) before taking further action.  So this would remove any "extra" file systems mounted under root, and would not wipe them via rm -r /  (since they're not mounted).

> Yes i'm aware of this, only star-gui.sh does that (reads backup.conf but any changes you make in the gui will override the conf file). This is by design and cannot be changed for several reasons.

Bummer but I understand.  Easily worked around by deleting or renaming /etc/backup.conf and supplying everything via command line options.

**My Testing:**  
I restored from a backup last night on my live system (i.e. not a vbox - living dangerously but had unmounted everything first, and didn't care if the restore failed - I've got installing a base Arch install down to < 10 mins now using a local pacman cache).  I first downloaded the latest scripts from GitHub.  They worked fine with my /dev/nvme... partitions, and wiped the root and home drives successfully.  I regressed from an Arch install with Mate, XFCE, Cinnamon, Xorg, & Wayland installed (plus a lot of junk), back to a clean base install, which was what I wanted.

I'll do further testing on the weekend and post my results.

(No reply expected to this post.  Thanks again for the great work and such a quick turnaround on these issues.)

**Comment by tritonas00** [comment]
> So this would unmount any partitions mounted under root

No, because the script simply doesn't accept already mounted partition (any of them not only root)

And you cant have something mounted to something that's not mounted first... :smile:

The script mounts and process your defined (and unmounted) partitions. If you give it a partition that's already mounted anywhere it will exit with a warning message

**Comment by tritonas00** [comment]
> would expect command line options to override any options saved in backup.conf

I think i fixed this issue harmlessly https://github.com/tritonas00/system-tar-and-restore/commit/cefbc569542177b77b9b2caecafa9561b5449518

Can you please give it a try?

**Comment by tritonas00** [comment]
> and wiped the root and home drives successfully

Closing this issue then, feel free to open a new issue.
