### ISSUE TITLE
What is the difference between RestoreMode and TransferMode?

### ISSUE THREAD

**Issue by 4qv907rtet5r** [tritonas00/system-tar-and-restore#8]
and another question.

Is **Live System Backup** possible?

**Comment by tritonas00** [comment]
Hi!

Restore Mode extracts a given backup archive in target partitions using tar
Transfer Mode transfers the current / in target partitions using rsync

What do you mean by "Live System Backup"?

**Comment by 4qv907rtet5r** [comment]
Hello! @tritonas00 

thanks for reply.

I want to boot sda and restore sdb.

Sometimes sda backup fails. but that's OK

and restore sdb and modify grub.cfg **from sdb to sda.**

Thank you for your project.

**Comment by tritonas00** [comment]
> I want to boot sda and restore sdb.

Then maybe you need Transfer Mode (no backup, just direct transfer from sda to sdb)

> Sometimes sda backup fails

Do you get error like "tar: file changed as we read it" ?

**Comment by 4qv907rtet5r** [comment]
When Transfer Mode, how can I specify source(sda), target(sdb)?

**Comment by tritonas00** [comment]
source is always the current /, so boot from the system you want to transfer

for the target partitions see star.sh --help or the examples here https://github.com/tritonas00/system-tar-and-restore#examples-using-arguments

**Comment by 4qv907rtet5r** [comment]
many thanks.

problem solved.
