### ISSUE TITLE
Any thought to implement a .desktop file for menu entry?

### ISSUE THREAD

**Issue by Petross404** [tritonas00/system-tar-and-restore#9]
Hi @tritonas00, I wrote an ebuild for Gentoo and already opened a bug in order for the Dev's to check it out. I think that a menu entry for the gui wrapper might be good.

It would require root's passwd and would also have a nice description, icon and stuff.

What do you think about it? Although I am kind of noob, I am willing to give a try and help you out with these. :)

**Comment by tritonas00** [comment]
Hi! (Γεια σου Πετρο!)

Yes not a bad idea.

Create the file `/usr/share/polkit-1/actions/org.freedesktop.policykit.star-gui.policy` http://pastebin.com/G6HuSy8h

and then `/usr/share/applications/System Tar & Restore.desktop`
http://pastebin.com/ACfa90d9

And give it a try

**Comment by Petross404** [comment]
Good afternoon :) Before I go to try these files, shouldn't be a better idea to not have spaces inside the .desktop filename?

**Comment by Petross404** [comment]
It works like a charm! Should these files be pushed in the repo?

**Comment by tritonas00** [comment]
> shouldn't be a better idea to not have spaces inside the .desktop filename?

I don't think this is  a problem, there are other .desktop launchers with spaces also

> Should these files be pushed in the repo?

Yes, i will do it

**Comment by tritonas00** [comment]
Files added under the `pms` dir.

**Comment by Petross404** [comment]
Will check later!

**Comment by Petross404** [comment]
Oh, of course you won't mind but I will see if I can install the .desktop without spaces (kind of rename it in the ebuild). Call me obsessive, but I think it won't hurt if I play it safely.

All the best, Petros

**Comment by tritonas00** [comment]
> kind of rename it in the ebuild

to make things simpler, i renamed it :smile:

**Comment by Petross404** [comment]
Nice! Thank you!

Keep up the good work ;)
